/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardPlanRouteImport } from './routes/dashboard/plan'
import { Route as DashboardPdfsRouteImport } from './routes/dashboard/pdfs'
import { Route as DashboardOdinRouteImport } from './routes/dashboard/odin'
import { Route as DashboardNotesRouteImport } from './routes/dashboard/notes'
import { Route as DashboardClassesRouteImport } from './routes/dashboard/classes'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardBudgetRouteImport } from './routes/dashboard/budget'
import { Route as DashboardBoardRouteImport } from './routes/dashboard/board'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as DashboardPdfsIndexRouteImport } from './routes/dashboard/pdfs/index'
import { Route as DashboardNotesIndexRouteImport } from './routes/dashboard/notes/index'
import { Route as DashboardClassesIndexRouteImport } from './routes/dashboard/classes/index'
import { Route as DashboardAssignmentsIndexRouteImport } from './routes/dashboard/assignments/index'
import { Route as DashboardPdfsPdfIdRouteImport } from './routes/dashboard/pdfs/$pdfId'
import { Route as DashboardNotesNoteIdRouteImport } from './routes/dashboard/notes/$noteId'
import { Route as DashboardClassesClassIdRouteImport } from './routes/dashboard/classes/$classId'
import { Route as DashboardAssignmentsAssignmentIdRouteImport } from './routes/dashboard/assignments/$assignmentId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanRoute = DashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPdfsRoute = DashboardPdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOdinRoute = DashboardOdinRouteImport.update({
  id: '/odin',
  path: '/odin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBudgetRoute = DashboardBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBoardRoute = DashboardBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPdfsIndexRoute = DashboardPdfsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPdfsRoute,
} as any)
const DashboardNotesIndexRoute = DashboardNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardNotesRoute,
} as any)
const DashboardClassesIndexRoute = DashboardClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClassesRoute,
} as any)
const DashboardAssignmentsIndexRoute =
  DashboardAssignmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAssignmentsRoute,
  } as any)
const DashboardPdfsPdfIdRoute = DashboardPdfsPdfIdRouteImport.update({
  id: '/$pdfId',
  path: '/$pdfId',
  getParentRoute: () => DashboardPdfsRoute,
} as any)
const DashboardNotesNoteIdRoute = DashboardNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => DashboardNotesRoute,
} as any)
const DashboardClassesClassIdRoute = DashboardClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => DashboardClassesRoute,
} as any)
const DashboardAssignmentsAssignmentIdRoute =
  DashboardAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => DashboardAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRouteWithChildren
  '/dashboard/odin': typeof DashboardOdinRoute
  '/dashboard/pdfs': typeof DashboardPdfsRouteWithChildren
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/dashboard/pdfs/$pdfId': typeof DashboardPdfsPdfIdRoute
  '/dashboard/assignments/': typeof DashboardAssignmentsIndexRoute
  '/dashboard/classes/': typeof DashboardClassesIndexRoute
  '/dashboard/notes/': typeof DashboardNotesIndexRoute
  '/dashboard/pdfs/': typeof DashboardPdfsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/odin': typeof DashboardOdinRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/dashboard/pdfs/$pdfId': typeof DashboardPdfsPdfIdRoute
  '/dashboard/assignments': typeof DashboardAssignmentsIndexRoute
  '/dashboard/classes': typeof DashboardClassesIndexRoute
  '/dashboard/notes': typeof DashboardNotesIndexRoute
  '/dashboard/pdfs': typeof DashboardPdfsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/board': typeof DashboardBoardRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRouteWithChildren
  '/dashboard/odin': typeof DashboardOdinRoute
  '/dashboard/pdfs': typeof DashboardPdfsRouteWithChildren
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
  '/dashboard/notes/$noteId': typeof DashboardNotesNoteIdRoute
  '/dashboard/pdfs/$pdfId': typeof DashboardPdfsPdfIdRoute
  '/dashboard/assignments/': typeof DashboardAssignmentsIndexRoute
  '/dashboard/classes/': typeof DashboardClassesIndexRoute
  '/dashboard/notes/': typeof DashboardNotesIndexRoute
  '/dashboard/pdfs/': typeof DashboardPdfsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/assignments'
    | '/dashboard/board'
    | '/dashboard/budget'
    | '/dashboard/chat'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard/odin'
    | '/dashboard/pdfs'
    | '/dashboard/plan'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
    | '/dashboard/notes/$noteId'
    | '/dashboard/pdfs/$pdfId'
    | '/dashboard/assignments/'
    | '/dashboard/classes/'
    | '/dashboard/notes/'
    | '/dashboard/pdfs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/board'
    | '/dashboard/budget'
    | '/dashboard/chat'
    | '/dashboard/odin'
    | '/dashboard/plan'
    | '/dashboard'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
    | '/dashboard/notes/$noteId'
    | '/dashboard/pdfs/$pdfId'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard/pdfs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/assignments'
    | '/dashboard/board'
    | '/dashboard/budget'
    | '/dashboard/chat'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard/odin'
    | '/dashboard/pdfs'
    | '/dashboard/plan'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
    | '/dashboard/notes/$noteId'
    | '/dashboard/pdfs/$pdfId'
    | '/dashboard/assignments/'
    | '/dashboard/classes/'
    | '/dashboard/notes/'
    | '/dashboard/pdfs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan': {
      id: '/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof DashboardPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pdfs': {
      id: '/dashboard/pdfs'
      path: '/pdfs'
      fullPath: '/dashboard/pdfs'
      preLoaderRoute: typeof DashboardPdfsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/odin': {
      id: '/dashboard/odin'
      path: '/odin'
      fullPath: '/dashboard/odin'
      preLoaderRoute: typeof DashboardOdinRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/budget': {
      id: '/dashboard/budget'
      path: '/budget'
      fullPath: '/dashboard/budget'
      preLoaderRoute: typeof DashboardBudgetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/board': {
      id: '/dashboard/board'
      path: '/board'
      fullPath: '/dashboard/board'
      preLoaderRoute: typeof DashboardBoardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pdfs/': {
      id: '/dashboard/pdfs/'
      path: '/'
      fullPath: '/dashboard/pdfs/'
      preLoaderRoute: typeof DashboardPdfsIndexRouteImport
      parentRoute: typeof DashboardPdfsRoute
    }
    '/dashboard/notes/': {
      id: '/dashboard/notes/'
      path: '/'
      fullPath: '/dashboard/notes/'
      preLoaderRoute: typeof DashboardNotesIndexRouteImport
      parentRoute: typeof DashboardNotesRoute
    }
    '/dashboard/classes/': {
      id: '/dashboard/classes/'
      path: '/'
      fullPath: '/dashboard/classes/'
      preLoaderRoute: typeof DashboardClassesIndexRouteImport
      parentRoute: typeof DashboardClassesRoute
    }
    '/dashboard/assignments/': {
      id: '/dashboard/assignments/'
      path: '/'
      fullPath: '/dashboard/assignments/'
      preLoaderRoute: typeof DashboardAssignmentsIndexRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
    '/dashboard/pdfs/$pdfId': {
      id: '/dashboard/pdfs/$pdfId'
      path: '/$pdfId'
      fullPath: '/dashboard/pdfs/$pdfId'
      preLoaderRoute: typeof DashboardPdfsPdfIdRouteImport
      parentRoute: typeof DashboardPdfsRoute
    }
    '/dashboard/notes/$noteId': {
      id: '/dashboard/notes/$noteId'
      path: '/$noteId'
      fullPath: '/dashboard/notes/$noteId'
      preLoaderRoute: typeof DashboardNotesNoteIdRouteImport
      parentRoute: typeof DashboardNotesRoute
    }
    '/dashboard/classes/$classId': {
      id: '/dashboard/classes/$classId'
      path: '/$classId'
      fullPath: '/dashboard/classes/$classId'
      preLoaderRoute: typeof DashboardClassesClassIdRouteImport
      parentRoute: typeof DashboardClassesRoute
    }
    '/dashboard/assignments/$assignmentId': {
      id: '/dashboard/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/dashboard/assignments/$assignmentId'
      preLoaderRoute: typeof DashboardAssignmentsAssignmentIdRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
  }
}

interface DashboardAssignmentsRouteChildren {
  DashboardAssignmentsAssignmentIdRoute: typeof DashboardAssignmentsAssignmentIdRoute
  DashboardAssignmentsIndexRoute: typeof DashboardAssignmentsIndexRoute
}

const DashboardAssignmentsRouteChildren: DashboardAssignmentsRouteChildren = {
  DashboardAssignmentsAssignmentIdRoute: DashboardAssignmentsAssignmentIdRoute,
  DashboardAssignmentsIndexRoute: DashboardAssignmentsIndexRoute,
}

const DashboardAssignmentsRouteWithChildren =
  DashboardAssignmentsRoute._addFileChildren(DashboardAssignmentsRouteChildren)

interface DashboardClassesRouteChildren {
  DashboardClassesClassIdRoute: typeof DashboardClassesClassIdRoute
  DashboardClassesIndexRoute: typeof DashboardClassesIndexRoute
}

const DashboardClassesRouteChildren: DashboardClassesRouteChildren = {
  DashboardClassesClassIdRoute: DashboardClassesClassIdRoute,
  DashboardClassesIndexRoute: DashboardClassesIndexRoute,
}

const DashboardClassesRouteWithChildren =
  DashboardClassesRoute._addFileChildren(DashboardClassesRouteChildren)

interface DashboardNotesRouteChildren {
  DashboardNotesNoteIdRoute: typeof DashboardNotesNoteIdRoute
  DashboardNotesIndexRoute: typeof DashboardNotesIndexRoute
}

const DashboardNotesRouteChildren: DashboardNotesRouteChildren = {
  DashboardNotesNoteIdRoute: DashboardNotesNoteIdRoute,
  DashboardNotesIndexRoute: DashboardNotesIndexRoute,
}

const DashboardNotesRouteWithChildren = DashboardNotesRoute._addFileChildren(
  DashboardNotesRouteChildren,
)

interface DashboardPdfsRouteChildren {
  DashboardPdfsPdfIdRoute: typeof DashboardPdfsPdfIdRoute
  DashboardPdfsIndexRoute: typeof DashboardPdfsIndexRoute
}

const DashboardPdfsRouteChildren: DashboardPdfsRouteChildren = {
  DashboardPdfsPdfIdRoute: DashboardPdfsPdfIdRoute,
  DashboardPdfsIndexRoute: DashboardPdfsIndexRoute,
}

const DashboardPdfsRouteWithChildren = DashboardPdfsRoute._addFileChildren(
  DashboardPdfsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRouteWithChildren
  DashboardBoardRoute: typeof DashboardBoardRoute
  DashboardBudgetRoute: typeof DashboardBudgetRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardClassesRoute: typeof DashboardClassesRouteWithChildren
  DashboardNotesRoute: typeof DashboardNotesRouteWithChildren
  DashboardOdinRoute: typeof DashboardOdinRoute
  DashboardPdfsRoute: typeof DashboardPdfsRouteWithChildren
  DashboardPlanRoute: typeof DashboardPlanRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRouteWithChildren,
  DashboardBoardRoute: DashboardBoardRoute,
  DashboardBudgetRoute: DashboardBudgetRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardClassesRoute: DashboardClassesRouteWithChildren,
  DashboardNotesRoute: DashboardNotesRouteWithChildren,
  DashboardOdinRoute: DashboardOdinRoute,
  DashboardPdfsRoute: DashboardPdfsRouteWithChildren,
  DashboardPlanRoute: DashboardPlanRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
