/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNotesRouteImport } from './routes/dashboard/notes'
import { Route as DashboardClassesRouteImport } from './routes/dashboard/classes'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard/assignments'
import { Route as DashboardClassesClassIdRouteImport } from './routes/dashboard/classes/$classId'
import { Route as DashboardAssignmentsAssignmentIdRouteImport } from './routes/dashboard/assignments/$assignmentId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotesRoute = DashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesClassIdRoute = DashboardClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => DashboardClassesRoute,
} as any)
const DashboardAssignmentsAssignmentIdRoute =
  DashboardAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => DashboardAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/classes': typeof DashboardClassesRouteWithChildren
  '/dashboard/notes': typeof DashboardNotesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/classes/$classId': typeof DashboardClassesClassIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/notes'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/classes/$classId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notes': {
      id: '/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof DashboardNotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes/$classId': {
      id: '/dashboard/classes/$classId'
      path: '/$classId'
      fullPath: '/dashboard/classes/$classId'
      preLoaderRoute: typeof DashboardClassesClassIdRouteImport
      parentRoute: typeof DashboardClassesRoute
    }
    '/dashboard/assignments/$assignmentId': {
      id: '/dashboard/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/dashboard/assignments/$assignmentId'
      preLoaderRoute: typeof DashboardAssignmentsAssignmentIdRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
  }
}

interface DashboardAssignmentsRouteChildren {
  DashboardAssignmentsAssignmentIdRoute: typeof DashboardAssignmentsAssignmentIdRoute
}

const DashboardAssignmentsRouteChildren: DashboardAssignmentsRouteChildren = {
  DashboardAssignmentsAssignmentIdRoute: DashboardAssignmentsAssignmentIdRoute,
}

const DashboardAssignmentsRouteWithChildren =
  DashboardAssignmentsRoute._addFileChildren(DashboardAssignmentsRouteChildren)

interface DashboardClassesRouteChildren {
  DashboardClassesClassIdRoute: typeof DashboardClassesClassIdRoute
}

const DashboardClassesRouteChildren: DashboardClassesRouteChildren = {
  DashboardClassesClassIdRoute: DashboardClassesClassIdRoute,
}

const DashboardClassesRouteWithChildren =
  DashboardClassesRoute._addFileChildren(DashboardClassesRouteChildren)

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRouteWithChildren
  DashboardClassesRoute: typeof DashboardClassesRouteWithChildren
  DashboardNotesRoute: typeof DashboardNotesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRouteWithChildren,
  DashboardClassesRoute: DashboardClassesRouteWithChildren,
  DashboardNotesRoute: DashboardNotesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
